# Generated by Django 2.2.4 on 2021-03-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(max_length=10)),
                ('power_mod', models.IntegerField()),
                ('speed_mod', models.IntegerField()),
                ('attack_mod', models.IntegerField()),
                ('damage_mod', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_recovery', models.IntegerField()),
                ('base_miss', models.IntegerField()),
                ('base_damage', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defense_type', models.CharField(max_length=10)),
                ('speed_mod', models.IntegerField()),
                ('agility_mod', models.IntegerField()),
                ('defense_mod', models.IntegerField()),
                ('recovery_mod', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
