# Generated by Django 2.2.4 on 2021-03-31 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0002_attack_base_defense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fighter1_health', models.IntegerField(default=100)),
                ('fighter2_health', models.IntegerField(default=100)),
                ('fight_round', models.IntegerField(default=1)),
                ('fight_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fighter1', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fighter1', to='combat_app.Fighter')),
                ('fighter2', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fighter2', to='combat_app.Fighter')),
            ],
        ),
    ]
