# Generated by Django 2.2.4 on 2021-03-31 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0003_fight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='attack_mod',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='attack',
            name='damage_mod',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='attack',
            name='power_mod',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='attack',
            name='speed_mod',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='base',
            name='base_miss',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='defense',
            name='agility_mod',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='defense',
            name='defense_mod',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='defense',
            name='recovery_mod',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='defense',
            name='speed_mod',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
