# Generated by Django 2.2.4 on 2021-04-01 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0004_auto_20210331_1801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fight',
            new_name='ActiveFight',
        ),
    ]
