# Generated by Django 2.2.4 on 2021-04-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0005_auto_20210331_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='base_parry',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
            preserve_default=False,
        ),
    ]
