# Generated by Django 2.2.4 on 2021-04-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0006_base_base_parry'),
    ]

    operations = [
        migrations.AddField(
            model_name='activefight',
            name='first_attack',
            field=models.BooleanField(default=False),
        ),
    ]
