# Generated by Django 2.2.4 on 2021-04-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0007_activefight_first_attack'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed_mod', models.DecimalField(decimal_places=2, max_digits=3)),
                ('attack_mod', models.DecimalField(decimal_places=2, max_digits=3)),
                ('agility_mod', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
