# Generated by Django 2.2.4 on 2021-04-01 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0008_firstattack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activefight',
            name='first_attack',
        ),
        migrations.CreateModel(
            name='CurrentAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attacker', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fighter', to='combat_app.ActiveFight')),
            ],
        ),
    ]
