# Generated by Django 2.2.4 on 2021-04-02 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0009_auto_20210401_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='FightAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attacker', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attacker', to='combat_app.ActiveFight')),
                ('defender', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defender', to='combat_app.ActiveFight')),
            ],
        ),
        migrations.DeleteModel(
            name='CurrentAttack',
        ),
    ]
