# Generated by Django 2.2.4 on 2021-04-02 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0010_auto_20210401_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='FighterHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fighter1', models.IntegerField(default=100)),
                ('fighter2', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='activefight',
            name='fighter1_health',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fighter1_health', to='combat_app.FighterHealth'),
        ),
        migrations.AlterField(
            model_name='activefight',
            name='fighter2_health',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fighter2_health', to='combat_app.FighterHealth'),
        ),
    ]
