# Generated by Django 2.2.4 on 2021-04-02 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0011_auto_20210401_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fighterhealth',
            old_name='fighter1',
            new_name='fighter1_health',
        ),
        migrations.RenameField(
            model_name='fighterhealth',
            old_name='fighter2',
            new_name='fighter2_health',
        ),
        migrations.AlterField(
            model_name='activefight',
            name='fighter1_health',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fighter1', to='combat_app.FighterHealth'),
        ),
        migrations.AlterField(
            model_name='activefight',
            name='fighter2_health',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fighter2', to='combat_app.FighterHealth'),
        ),
    ]
