# Generated by Django 2.2.4 on 2021-04-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0013_auto_20210401_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighterhealth',
            name='fighter',
            field=models.CharField(max_length=20),
        ),
    ]
