# Generated by Django 2.2.4 on 2021-04-02 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0014_auto_20210401_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activefight',
            name='fighter1_health',
        ),
        migrations.RemoveField(
            model_name='activefight',
            name='fighter2_health',
        ),
    ]
