# Generated by Django 2.2.4 on 2021-04-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0015_auto_20210401_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighterhealth',
            name='fighter',
            field=models.IntegerField(default=1),
        ),
    ]
