# Generated by Django 2.2.4 on 2021-04-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0016_auto_20210402_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fightaction',
            name='attacker',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fightaction',
            name='defender',
            field=models.IntegerField(default=1),
        ),
    ]
