# Generated by Django 2.2.4 on 2021-04-12 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0018_techniquemods'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechniqueMods',
            new_name='TechniqueMod',
        ),
    ]
